# Generated by Django 5.2.5 on 2025-09-13 11:15

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('sname', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255, null=True)),
                ('weight_class', models.CharField(choices=[('SW', 'Strawweight'), ('FLY', 'Flyweight'), ('BW', 'Bantamweight'), ('FW', 'Featherweight'), ('LW', 'Lightweight'), ('WW', 'Welterweight'), ('MW', 'Middleweight'), ('LHW', 'Light Heavyweight'), ('HW', 'Heavyweight'), ('SHW', 'Super Heavyweight'), ('CW', 'Catchweight')], max_length=255)),
                ('dob', models.DateField()),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('losses', models.PositiveSmallIntegerField(default=0)),
                ('draws', models.PositiveSmallIntegerField(default=0)),
                ('no_contests', models.PositiveSmallIntegerField(default=0)),
                ('dqs', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('UFC', 'Ultimate Fighting Championship'), ('PFL', 'Professional Fighters League'), ('Bellator', 'Bellator MMA'), ('ONE', 'ONE Championship')], max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_class', models.CharField(choices=[('SW', 'Strawweight'), ('FLY', 'Flyweight'), ('BW', 'Bantamweight'), ('FW', 'Featherweight'), ('LW', 'Lightweight'), ('WW', 'Welterweight'), ('MW', 'Middleweight'), ('LHW', 'Light Heavyweight'), ('HW', 'Heavyweight'), ('SHW', 'Super Heavyweight'), ('CW', 'Catchweight')], max_length=255)),
                ('scheduled_rounds', models.PositiveSmallIntegerField(default=3)),
                ('title_fight', models.BooleanField()),
                ('method', models.CharField(choices=[('DEC', 'Decision'), ('SUB', 'Submission'), ('TKO', 'Technical Knockout'), ('KO', 'Knockout'), ('DQ', 'Disqualification'), ('NC', 'No Contest')], max_length=255)),
                ('round', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.event')),
                ('fighter_blue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blue_corner', to='api.fighter')),
                ('fighter_red', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_corner', to='api.fighter')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.fighter')),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_odds_red', models.FloatField()),
                ('decimal_odds_blue', models.FloatField()),
                ('bookmaker', models.CharField(choices=[('Bet365', 'Bet365'), ('PaddyPower', 'Paddypower')], max_length=255)),
                ('date', models.DateField()),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fight')),
            ],
            options={
                'unique_together': {('fight', 'decimal_odds_red', 'decimal_odds_blue', 'bookmaker')},
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('DEC', 'Decision'), ('SUB', 'Submission'), ('TKO', 'Technical Knockout'), ('KO', 'Knockout'), ('DQ', 'Disqualification'), ('NC', 'No Contest')], max_length=255, null=True)),
                ('round', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect'), ('PARTIALLY_CORRECT', 'Partially Correct')], max_length=255)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fight')),
                ('odds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.odds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fighter')),
            ],
        ),
        migrations.AddField(
            model_name='fighter',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.promotion'),
        ),
        migrations.AddField(
            model_name='event',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.promotion'),
        ),
    ]
