# Generated by Django 6.0 on 2026-01-10 16:34

import api.models.fighter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.fighter.fighter_image_upload_path),
        ),
    ]
