# Generated by Django 6.0 on 2026-01-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fighter_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='image',
            new_name='avatar',
        ),
    ]
