# Generated by Django 6.0 on 2026-01-11 16:10

import api.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_image_fighter_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.utils.promotion_image_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.utils.user_image_upload_path),
        ),
    ]
