# Generated by Django 5.2.5 on 2025-11-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_prediction_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Odds',
        ),
    ]
