# Generated by Django 6.0 on 2026-01-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_prediction_prediction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='winning_method',
            field=models.CharField(blank=True, choices=[('FINISH', 'Finish'), ('KO/TKO', 'Knockout/Technical Knockout'), ('DEC', 'Decision'), ('DEC-SPLIT', 'Split Decision'), ('SUB', 'Submission'), ('TKO', 'Technical Knockout'), ('KO', 'Knockout'), ('DQ', 'Disqualification'), ('NC', 'No Contest')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='predicted_method',
            field=models.CharField(blank=True, choices=[('FINISH', 'Finish'), ('KO/TKO', 'Knockout/Technical Knockout'), ('DEC', 'Decision'), ('DEC-SPLIT', 'Split Decision'), ('SUB', 'Submission'), ('TKO', 'Technical Knockout'), ('KO', 'Knockout'), ('DQ', 'Disqualification'), ('NC', 'No Contest')], max_length=255, null=True),
        ),
    ]
