# Generated by Django 6.0 on 2026-01-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_fight_winning_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='winning_method',
            field=models.CharField(blank=True, choices=[('FINISH', 'Finish'), ('KO/TKO', 'Kotko'), ('DEC', 'Dec'), ('DEC-SPLIT', 'Split'), ('SUB', 'Sub'), ('KO', 'Ko'), ('DQ', 'Dq'), ('NC', 'Noc')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='predicted_method',
            field=models.CharField(blank=True, choices=[('FINISH', 'Finish'), ('KO/TKO', 'Kotko'), ('DEC', 'Dec'), ('DEC-SPLIT', 'Split'), ('SUB', 'Sub'), ('KO', 'Ko'), ('DQ', 'Dq'), ('NC', 'Noc')], max_length=255, null=True),
        ),
    ]
