# Generated by Django 6.0 on 2026-01-05 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='method',
            field=models.CharField(blank=True, choices=[('DEC', 'Decision'), ('DEC-SPLIT', 'Split Decision'), ('SUB', 'Submission'), ('TKO', 'Technical Knockout'), ('KO', 'Knockout'), ('DQ', 'Disqualification'), ('NC', 'No Contest')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.fighter'),
        ),
    ]
