# Generated by Django 6.0 on 2026-01-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_fight_method_alter_fight_round_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fight',
            old_name='method',
            new_name='winning_method',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='round',
            new_name='winning_round',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='title_fight',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=255),
        ),
        migrations.AddField(
            model_name='fight',
            name='fighter_blue_record',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='fighter_red_record',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='is_main_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fight',
            name='is_title_fight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fight',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=255),
        ),
    ]
