# Generated by Django 6.0 on 2026-01-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_prediction_perfect_prediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
