# Generated by Django 6.0 on 2026-01-30 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_fighter_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_predictions', models.IntegerField(default=0)),
                ('winner_correct_count', models.IntegerField(default=0)),
                ('perfect_prediction_count', models.IntegerField(default=0)),
                ('winner_and_dec_or_finish_correct_count', models.IntegerField(default=0)),
                ('winner_and_method_correct_count', models.IntegerField(default=0)),
                ('winner_and_round_correct_count', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
            ],
        ),
    ]
