# Generated by Django 6.0 on 2026-01-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstats',
            old_name='winner_and_dec_or_finish_correct_count',
            new_name='winner_and_decision_count',
        ),
        migrations.AddField(
            model_name='prediction',
            name='decision_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='finish_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='winner_and_finish_count',
            field=models.IntegerField(default=0),
        ),
    ]
