# Generated by Django 6.0 on 2026-01-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_winner_and_dec_or_finish_correct_count_userstats_winner_and_decision_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstats',
            old_name='winner_and_decision_count',
            new_name='winner_and_decision_correct_count',
        ),
        migrations.RenameField(
            model_name='userstats',
            old_name='winner_and_finish_count',
            new_name='winner_and_finish_correct_count',
        ),
    ]
