# Generated by Django 6.0 on 2026-02-12 21:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
