# Generated by Django 6.0 on 2026-02-12 22:08

import django_countries.fields
import fightoracle_api.settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_fighter_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='country',
            field=django_countries.fields.CountryField(blank=True, countries=fightoracle_api.settings.CustomCountries, max_length=2, null=True),
        ),
    ]
