# Generated by Django 6.0 on 2026-02-14 14:06

import api.options
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_fighter_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='reach',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='country',
            field=django_countries.fields.CountryField(blank=True, countries=api.options.CustomCountries, max_length=3, null=True),
        ),
    ]
